"use client";
import { useState } from "react";
import Link from "next/link";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Sparkles,
  TrendingUp,
  TrendingDown,
  Minus,
  Calendar,
  PlayCircle,
  Brain,
} from "lucide-react";
import { apiGet, apiPost, type Run, type Order } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";

type Bucket = "today" | "yesterday" | "week";

export default function RecommendationsPage() {
  const qc = useQueryClient();
  const [tab, setTab] = useState<Bucket>("today");
  const [staging, setStaging] = useState<number | null>(null);

  const { data: runs } = useQuery({
    queryKey: ["runs", "all-200"],
    queryFn: () => apiGet<Run[]>("/runs?limit=200"),
    refetchInterval: 30_000,
  });

  // Filter runs by bucket
  const now = new Date();
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
  const yesterdayStart = todayStart - 86400000;
  const weekStart = todayStart - 7 * 86400000;

  const filtered = (runs ?? []).filter((r) => {
    if (r.status !== "completed") return false;
    const t = new Date(r.started_at).getTime();
    if (tab === "today") return t >= todayStart;
    if (tab === "yesterday") return t >= yesterdayStart && t < todayStart;
    return t >= weekStart;
  });

  // Group by ticker — keep latest signal per ticker
  const byTicker = new Map<string, Run>();
  for (const r of filtered) {
    const prev = byTicker.get(r.ticker);
    if (!prev || new Date(r.started_at) > new Date(prev.started_at)) {
      byTicker.set(r.ticker, r);
    }
  }
  const recs = Array.from(byTicker.values()).sort((a, b) => {
    const order = (s: string | null) => {
      const x = (s || "").toUpperCase();
      if (x.includes("STRONG BUY") || x.includes("OVERWEIGHT")) return 0;
      if (x.includes("BUY")) return 1;
      if (x.includes("HOLD")) return 2;
      if (x.includes("SELL") || x.includes("UNDERWEIGHT")) return 3;
      return 4;
    };
    return order(a.signal) - order(b.signal);
  });

  const buys = recs.filter((r) => /BUY|OVERWEIGHT/i.test(r.signal ?? ""));
  const sells = recs.filter((r) => /SELL|UNDERWEIGHT/i.test(r.signal ?? ""));
  const holds = recs.filter((r) => /HOLD/i.test(r.signal ?? ""));

  async function stage(runId: number) {
    setStaging(runId);
    try {
      const o = (await apiPost<Order>(`/trades/from-run/${runId}`)) as Order;
      if (o.status === "rejected" || o.status === "hold") {
        toast.warning(`Order ${o.status}`, { description: o.rejection_reason ?? "no action" });
      } else {
        toast.success("Order staged → Trades", { description: `${o.symbol} ${o.side} ${o.qty}` });
      }
      qc.invalidateQueries({ queryKey: ["trades"] });
    } catch (e) {
      toast.error("Stage failed", { description: String(e) });
    } finally {
      setStaging(null);
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <div className="mb-1 flex items-center gap-2 text-xs uppercase tracking-wider text-muted-foreground">
          <Calendar className="h-3.5 w-3.5 text-primary" />
          Daily recommendations
        </div>
        <h1 className="text-2xl font-semibold tracking-tight md:text-3xl">
          Today's agent picks
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Auto-generated by scheduled scans. Default: 9 AM and 4:30 PM ET (16:00 / 23:30 Istanbul).
          Edit schedules on{" "}
          <Link href="/schedules" className="text-primary hover:underline">
            /schedules
          </Link>
          .
        </p>
      </div>

      {/* Quick stats */}
      <div className="grid grid-cols-3 gap-4">
        <SummaryCard label="Buy signals" count={buys.length} tone="emerald" Icon={TrendingUp} />
        <SummaryCard label="Sell signals" count={sells.length} tone="red" Icon={TrendingDown} />
        <SummaryCard label="Hold" count={holds.length} tone="muted" Icon={Minus} />
      </div>

      <Tabs value={tab} onValueChange={(v) => setTab(v as Bucket)}>
        <TabsList>
          <TabsTrigger value="today">Today ({recs.length})</TabsTrigger>
          <TabsTrigger value="yesterday">Yesterday</TabsTrigger>
          <TabsTrigger value="week">Last 7 days</TabsTrigger>
        </TabsList>
        <TabsContent value={tab} className="space-y-3 pt-4">
          {recs.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center text-sm text-muted-foreground">
                No recommendations for this period yet. The next scheduled scan will populate this view.
              </CardContent>
            </Card>
          ) : (
            <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
              {recs.map((r) => (
                <RecCard key={r.id} run={r} onStage={() => stage(r.id)} staging={staging === r.id} />
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}

function SummaryCard({
  label,
  count,
  tone,
  Icon,
}: {
  label: string;
  count: number;
  tone: "emerald" | "red" | "muted";
  Icon: React.ComponentType<{ className?: string }>;
}) {
  const colors = {
    emerald: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
    red: "bg-red-500/10 text-red-600 dark:text-red-400",
    muted: "bg-muted text-muted-foreground",
  }[tone];
  return (
    <Card>
      <CardContent className="p-4">
        <div className="flex items-center justify-between">
          <div className="text-xs uppercase tracking-wider text-muted-foreground">{label}</div>
          <div className={`rounded-md ${colors} p-1.5`}>
            <Icon className="h-4 w-4" />
          </div>
        </div>
        <div className="mt-2 text-3xl font-semibold tracking-tight">{count}</div>
      </CardContent>
    </Card>
  );
}

function RecCard({
  run,
  onStage,
  staging,
}: {
  run: Run;
  onStage: () => void;
  staging: boolean;
}) {
  const sig = (run.signal ?? "").toUpperCase();
  const isBuy = /BUY|OVERWEIGHT/.test(sig);
  const isSell = /SELL|UNDERWEIGHT/.test(sig);
  const tone = isBuy
    ? "border-emerald-500/40 bg-emerald-500/5"
    : isSell
      ? "border-red-500/40 bg-red-500/5"
      : "border bg-card";
  const sigCls = isBuy
    ? "text-emerald-600 dark:text-emerald-400"
    : isSell
      ? "text-red-600 dark:text-red-400"
      : "text-muted-foreground";

  // Try to extract price target from decision text
  const targetMatch = run.final_decision?.match(/Price Target.*?(\d+\.?\d*)/i);
  const horizonMatch = run.final_decision?.match(/Time Horizon.*?:?\s*([^\n*]+)/i);

  return (
    <Card className={tone}>
      <CardContent className="space-y-3 p-4">
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2">
              <Link
                href={`/runs/${run.id}`}
                className="text-xl font-semibold hover:underline"
              >
                {run.ticker}
              </Link>
              <Badge variant="secondary" className="text-[10px]">
                #{run.id}
              </Badge>
            </div>
            <div className="text-[11px] text-muted-foreground">
              {new Date(run.started_at).toLocaleString("en-US", {
                month: "short",
                day: "numeric",
                hour: "2-digit",
                minute: "2-digit",
              })}
            </div>
          </div>
          <div className={`text-right ${sigCls}`}>
            <div className="text-lg font-bold">{run.signal}</div>
          </div>
        </div>

        {(targetMatch || horizonMatch) && (
          <div className="grid grid-cols-2 gap-2 rounded-lg border bg-card/50 p-2 text-xs">
            {targetMatch && (
              <div>
                <div className="text-muted-foreground">Target</div>
                <div className="font-mono font-semibold">${targetMatch[1]}</div>
              </div>
            )}
            {horizonMatch && (
              <div>
                <div className="text-muted-foreground">Horizon</div>
                <div className="font-medium">{horizonMatch[1].trim()}</div>
              </div>
            )}
          </div>
        )}

        {run.final_decision && (
          <p className="line-clamp-3 text-xs text-foreground/70">
            {run.final_decision.replace(/\*\*/g, "").slice(0, 240)}
          </p>
        )}

        <div className="flex gap-2">
          <Button onClick={onStage} disabled={staging} className="flex-1 gap-2" size="sm">
            <PlayCircle className="h-3.5 w-3.5" />
            {staging ? "Staging..." : "Stage order"}
          </Button>
          <Link
            href={`/runs/${run.id}`}
            className="inline-flex items-center justify-center rounded-md border bg-background px-3 text-xs hover:bg-accent"
          >
            <Brain className="h-3.5 w-3.5" />
          </Link>
        </div>
      </CardContent>
    </Card>
  );
}
